global:
  keycloak:
    url: "http://activiti-keycloak.jx-staging.35.228.195.195.nip.io/auth"
  gateway:
    host: &gatewayhost "activiti-cloud-gateway.jx-staging.35.228.195.195.nip.io"

activiti-cloud-full-example:
  activiti-cloud-modeling:
    enabled: true
